### PR TITLE
Update Miri invocation in CI

### LINKED ISSUE #45: Miri flag passing changed
`cargo miri test` changed to be more compatible with `cargo test`, but this means we had to find a different way to pass flags to the interpreter, so there now is a `MIRIFLAGS` environment variable for that. The old way still works for now, but is deprecated.

This affects the following line:
https://github.com/artichoke/intaglio/blob/3697f897b49d2f47446f0f8679a220a722b5898b/.github/workflows/miri.yaml#L36
This should now be `cargo miri test drop`, which runs the same tests as `cargo test drop`.

### PR DESCRIPTION
**Pull request by lopopolo**
Miri flag passing changed. Fixed #45.

### CODE REVIEW

**Comment by lopopolo** [comment]
Miri tests failed with:

```
     Running target/x86_64-unknown-linux-gnu/debug/deps/intaglio-f9786b8e4256ba13
thread 'main' panicked at 'all extern filenames should end in `.rlib`', src/tools/miri/cargo-miri/bin.rs:666:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1fd5b9d516c035a898dcb437b2f982bea5d4bc88/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/1fd5b9d516c035a898dcb437b2f982bea5d4bc88/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/1fd5b9d516c035a898dcb437b2f982bea5d4bc88/library/core/src/option.rs:1213
   3: cargo_miri::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: test failed, to rerun pass '--lib'
```

Tests used this nightly:

```
  nightly-x86_64-unknown-linux-gnu installed - rustc 1.48.0-nightly (1fd5b9d51 2020-09-20)
```

@RalfJung did I do something wrong with this upgrade, per #45?

**Comment by RalfJung** [comment]
Thanks for the quick reaction and sorry for this. This is a Miri issue that only shows up when certain proc macro crates are in the dependency tree. It is fixed in Miri now, I hope the fix will make it to the next nightly.

**Comment by lopopolo** [comment]
Thank you. 🙏 

I'll rebuild in a couple of days and merge this.

**Comment by RalfJung** [comment]
The new nightly is out, this should work now. :) Sorry for the delay.

**Comment by lopopolo** [comment]
Kicked the build. It passes now. 📈 🚀 

Thanks @RalfJung.

**Pull request merged**
